apiVersion: apps/v1
kind: Deployment
metadata:
  name: fanfliks-api
  namespace: fanfliks-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fanfliks-api
  template:
    metadata:
      labels:
        app: fanfliks-api
    spec:
      containers:
      - name: fanfliks-api
        image: shivushiv/fanfliks:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fanfliks-api-service
  namespace: fanfliks-dev
spec:
  selector:
    app: fanfliks-api
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
