version: '3.7'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    healthcheck:
      test: "echo 'db.runCommand({ping: 1})' | mongosh --quiet"
      interval: 10s
      timeout: 5s
      retries: 5

  mms-api:
    container_name: fanfliks-api
    image: fanfliks:api-1.0.1
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - ./mms.pfx:/https/mms.pfx
    ports:
      - "7001:7001"