# Use the official Ubuntu base image
FROM ubuntu:20.04

# Set the working directory to /app
WORKDIR /app

# Set the maintainer label
LABEL maintainer="harikumar.reddy@mindmatrix.net"

# Expose the necessary ports
EXPOSE 7001

# Install dependencies
RUN apt-get update && apt-get install -y \
    wget \
    apt-transport-https \
    curl \
    && wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y aspnetcore-runtime-8.0 \
    && rm packages-microsoft-prod.deb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy the published files into the container
COPY publish/* ./
COPY jwt.crt jwt.crt

# Set environment variable to specify the URL the application should listen on
ENV ASPNETCORE_URLS=http://0.0.0.0:7001

# Set the entry point to run the application
ENTRYPOINT ["dotnet", "api.dll"]